# install docker, eksctl, kubectl,and do aws configure in ec2 instance then create cluster
# eksctl create cluster --config-file=ekscluster/manifest.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1
managedNodeGroups:
  - name: roboshop-dev
    instanceTypes: ["m5.large","t3.small", "t3.medium","c5.large"]
    desiredCapacity: 2 #  by default this value is 3
    spot: true