apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  nameSpace: roboshop
  # kubectl config set-context --current --namespace=roboshop -> to make out roboshopnamespace as default namespace
  labels:
    purpose: niginx
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
