apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: roboshop
  # labels are used to filter and selecct the pod
  labels:
    purpose: niginx
    name: nginx
    environment: development
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
