apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  namespace: roboshop
  # These labels are used to register this pod with service
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx